### ISSUE TITLE
Request to join this organization

### ISSUE THREAD

**Issue by logeshpalani30** [msmvps/join-this-organization#100]
My MVP Profile is: https://mvp.microsoft.com/en-us/PublicProfile/5004431?fullName=Logesh%20Palani

- [x] Send the invitation to my GitHub listed on my MVP profile above

or

- [x] Send the invitation to my e-mail address listed on my MVP profile above

**Comment by augustoproiete** [comment]
@logeshpalani30 Invite sent to https://github.com/logeshpalani30
