### ISSUE TITLE
Request to join this organization

### ISSUE THREAD

**Issue by michaelstephensonuk** [msmvps/join-this-organization#101]
My MVP Profile is: https://mvp.microsoft.com/en-us/PublicProfile/4021792?fullName=michael%20stephenson

- [x] Send the invitation to my GitHub listed on my MVP profile above

or

- [x] Send the invitation to my e-mail address listed on my MVP profile above

**Comment by augustoproiete** [comment]
@michaelstephensonuk You have already joined the org. Let me know if there's anything else missing
