### ISSUE TITLE
Request to join this organization

### ISSUE THREAD

**Issue by LucioMSP** [msmvps/join-this-organization#103]
My MVP Profile is: https://mvp.microsoft.com/es-es/PublicProfile/5000948?fullName=Vicente%20Gerardo%20Guzm%C3%A1n%20Lucio

- [X] Send the invitation to my GitHub listed on my MVP profile above

**Comment by augustoproiete** [comment]
Hey @LucioMSP your GitHub profile doesn't seem to be visible on your MVP profile. Could you take a look?

![image](https://user-images.githubusercontent.com/177608/176808422-6e0b2a7a-c5d1-4021-b2b7-9a0fea6eddfa.png)

**Comment by LucioMSP** [comment]
Hi, 

I can't edit it, the page is under maintenance until July 5:

![image](https://user-images.githubusercontent.com/6353852/176903069-f5e6057d-a7b4-4ef1-8f32-6d8a24aff274.png)

**Comment by augustoproiete** [comment]
Invite sent to https://github.com/LucioMSP
