### ISSUE TITLE
Request to join this organization

### ISSUE THREAD

**Issue by karenpayneoregon** [msmvps/join-this-organization#104]
My MVP Profile is: https://mvp.microsoft.com/en-us/PublicProfile/5001096?fullName=Karen%20S%20Payne

- [ X] Send the invitation to my GitHub listed on my MVP profile above

or

- [ ] Send the invitation to my e-mail address listed on my MVP profile above

**Comment by augustoproiete** [comment]
Invite sent to https://github.com/karenpayneoregon/
