### ISSUE TITLE
Request to join this organization

### ISSUE THREAD

**Issue by yanjinhuagood** [msmvps/join-this-organization#109]
My MVP Profile is: https://mvp.microsoft.com/zh-cn/PublicProfile/5004941?fullName=JinHua%20%20Yan

- [x] Send the invitation to my GitHub listed on my MVP profile above

**Comment by augustoproiete** [comment]
@yanjinhuagood Your Github profile URL is not visible in your MVP profile

<img width="261" alt="image" src="https://user-images.githubusercontent.com/177608/188270697-cd68d722-45ab-46bf-82e9-dc9a4630638a.png">

I sent an invite to the email address listed in the MVP profile

**Comment by yanjinhuagood** [comment]
thanks！
