### ISSUE TITLE
Request to join this organization

### ISSUE THREAD

**Issue by mjtpena** [msmvps/join-this-organization#112]
My MVP Profile is: https://mvp.microsoft.com/en-us/PublicProfile/5001648?fullName=Michael%20John%20Timpoc%20Pe%C3%B1a

- [x] Send the invitation to my GitHub listed on my MVP profile above

or

- [ ] Send the invitation to my e-mail address listed on my MVP profile above

**Comment by augustoproiete** [comment]
@mjtpena You're already a member of this org. Let me know if you have any questions
