### ISSUE TITLE
Request to join this organization

### ISSUE THREAD

**Issue by marc-mueller** [msmvps/join-this-organization#113]
My MVP Profile is: https://mvp.microsoft.com/en-us/PublicProfile/5000589?fullName=Marc%20M%C3%BCller

- [x] Send the invitation to my GitHub listed on my MVP profile above

or

- [ ] Send the invitation to my e-mail address listed on my MVP profile above

**Comment by augustoproiete** [comment]
Invite sent to https://github.com/marc-mueller
