### ISSUE TITLE
Request to join this organization

### ISSUE THREAD

**Issue by samuelbarrionuevo** [msmvps/join-this-organization#120]
My MVP Profile is: [samuelbarrionuevo](https://github.com/samuelbarrionuevo)

- [ ] Send the invitation to my GitHub listed on my MVP profile above

or

- [ ] Send the invitation to my e-mail address listed on my MVP profile above

**Comment by augustoproiete** [comment]
@samuelbarrionuevo you need to be part of the Microsoft MVP program in order to join this organization
