### ISSUE TITLE
Request to join this organization

### ISSUE THREAD

**Issue by daixiang0** [msmvps/join-this-organization#125]
My MVP Profile is: https://mvp.microsoft.com/zh-cn/PublicProfile/5005074?fullName=Loong%20Dai

- [x] Send the invitation to my GitHub listed on my MVP profile above

**Comment by augustoproiete** [comment]
Your GitHub profile is not currently visible in your MVP profile. Ping back once you make it available there:

<img width="703" alt="image" src="https://user-images.githubusercontent.com/177608/206023974-35df7380-0c94-40d6-bc2a-b52229a93d69.png">

**Comment by daixiang0** [comment]
Please refresh and get it :)

**Comment by augustoproiete** [comment]
@daixiang0 Still not showing up for me (try opening your profile on an incognito window)

**Comment by daixiang0** [comment]
I can see it from MyProfile, not sure when it updates, you can wait or send it to this account(same as shown in my profile), thanks.

**Comment by daixiang0** [comment]
@augustoproiete now it updates

**Comment by augustoproiete** [comment]
Great. Now it's visible on your profile. Invite sent to https://github.com/daixiang0
