### ISSUE TITLE
Request to join this organization

### ISSUE THREAD

**Issue by lyzhang1999** [msmvps/join-this-organization#129]
My MVP Profile is: https://mvp.microsoft.com/zh-cn/PublicProfile/5005123?fullName=wei%20wang

- [x] Send the invitation to my GitHub listed on my MVP profile above

**Comment by augustoproiete** [comment]
@lyzhang1999 There's no GitHub profile on the MVP profile you linked above:

<img width="243" alt="image" src="https://user-images.githubusercontent.com/177608/210601235-86846b30-5704-497d-897f-ce35156a6c2e.png">

**Comment by augustoproiete** [comment]
Cool. Invite sent to https://github.com/lyzhang1999
