### ISSUE TITLE
Request to join this organization

### ISSUE THREAD

**Issue by emimontesdeoca** [msmvps/join-this-organization#135]
My MVP Profile is: https://mvp.microsoft.com/en-us/PublicProfile/5004972?fullName=Emiliano%20Martin%20Montesdeoca%20del%20Puerto

- [x] Send the invitation to my GitHub listed on my MVP profile above (**emimontesdeoca@outlook.es**)

or

- [ ] Send the invitation to my e-mail address listed on my MVP profile above

**Comment by augustoproiete** [comment]
Invitation sent to https://github.com/emimontesdeoca
