### ISSUE TITLE
Request to join this organization

### ISSUE THREAD

**Issue by mmisztal1980** [msmvps/join-this-organization#136]
My MVP Profile is: https://mvp.microsoft.com/en-us/PublicProfile/5003984?fullName=Maciej%20Misztal

- [] Send the invitation to my GitHub listed on my MVP profile above

or

- [x] Send the invitation to my e-mail address listed on my MVP profile above

**Comment by augustoproiete** [comment]
@mmisztal1980 Your GitHub profile is not being displayed in your MVP profile... Make sure to set the visibility to `Public`

<img width="247" alt="image" src="https://user-images.githubusercontent.com/177608/224193857-19544f8e-84d0-4541-8e3e-ec94bef92fa3.png">

**Comment by augustoproiete** [comment]
@mmisztal1980 It's still not visible to me - maybe there's caching.

Ping me here once you can see the link to your GitHub profile **in an incognito session**

**Comment by augustoproiete** [comment]
Invite sent to https://github.com/mmisztal1980
