### ISSUE TITLE
Request to join this organization

### ISSUE THREAD

**Issue by jiaopengzi** [msmvps/join-this-organization#137]
My MVP Profile is: https://mvp.microsoft.com/en-us/PublicProfile/5005257?fullName=Yijun%20Peng

- [ ] Send the invitation to my GitHub listed on my MVP profile above

or

- [ ] Send the invitation to my e-mail address listed on my MVP profile above

**Comment by augustoproiete** [comment]
Invite sent to [jiaopengzi@qq.com](mailto:jiaopengzi@qq.com)
