### ISSUE TITLE
Request to join this organization

### ISSUE THREAD

**Issue by goretsky** [msmvps/join-this-organization#142]
My MVP Profile is: https://mvp.microsoft.com/en-us/PublicProfile/10023?fullName=Aryeh%20Goretsky
- [X] Send the invitation to my GitHub listed on my MVP profile above

or

- [ ] Send the invitation to my e-mail address listed on my MVP profile above

**Comment by augustoproiete** [comment]
Invite sent to https://github.com/goretsky
