### ISSUE TITLE
Request to join this organization

### ISSUE THREAD

**Issue by p770820** [msmvps/join-this-organization#143]
I am rMVP

My MVP Profile is: https://mvp.microsoft.com/en-us/PublicProfile/5001510?fullName=Peter%20%20Chang

- [ ] Send the invitation to my GitHub listed on my MVP profile above

or

- [x] Send the invitation to my e-mail address listed on my MVP profile above

**Comment by augustoproiete** [comment]
Invite sent to p770820@gmail.com
