### ISSUE TITLE
Request to join this organization

### ISSUE THREAD

**Issue by CordoWEB** [msmvps/join-this-organization#144]
My rMVP Profile is: https://mvp.microsoft.com/fr-fr/PublicProfile/8543

- [ ] Send the invitation to my GitHub listed on my MVP profile above

or

- [ X] Send the invitation to my e-mail address listed on my MVP profile above

Thanks a lot :)

**Comment by augustoproiete** [comment]
Invite sent to christophe@cordoweb.net

**Comment by CordoWEB** [comment]
Thank you so much :)
