### ISSUE TITLE
Request to join this organization

### ISSUE THREAD

**Issue by domdeger** [msmvps/join-this-organization#149]
My MVP Profile is: https://mvp.microsoft.com/en-us/PublicProfile/5005324?fullName=Dominik%20Deschner

- [x] Send the invitation to my GitHub listed on my MVP profile above

or

- [ ] Send the invitation to my e-mail address listed on my MVP profile above

**Comment by augustoproiete** [comment]
@domdeger Your GitHub profile is not visible to the public on your MVP profile (as of this writing).

Please ping here once it's public.

<img width="313" alt="image" src="https://github.com/msmvps/join-this-organization/assets/177608/fd98c010-e9d4-48f7-a91e-f80481693f43">

**Comment by augustoproiete** [comment]
Invite sent to https://github.com/domdeger
