### ISSUE TITLE
Request to join this organization

### ISSUE THREAD

**Issue by dotnetgoo** [msmvps/join-this-organization#151]
My MVP Profile is: https://mvp.microsoft.com/en-us/PublicProfile/5005165?fullName=Mukhammadkarim%20Khusniddin%20Tukhtaboev

- [x] Send the invitation to my GitHub listed on my MVP profile above

or

- [x] Send the invitation to my e-mail address listed on my MVP profile above

**Comment by augustoproiete** [comment]
Invitation sent to https://github.com/dotnetgoo
