### ISSUE TITLE
Request to join this organization

### ISSUE THREAD

**Issue by MingsonZheng** [msmvps/join-this-organization#156]
My MVP Profile is: https://mvp.microsoft.com/zh-CN/mvp/profile/14112519-cdb0-ec11-983f-000d3a1017e3

- [ ✔] Send the invitation to my GitHub listed on my MVP profile above

or

- [ ] Send the invitation to my e-mail address listed on my MVP profile above

**Comment by augustoproiete** [comment]
Invitation sent to https://github.com/MingsonZheng
