### ISSUE TITLE
Request to join this organization

### ISSUE THREAD

**Issue by JayRHa** [msmvps/join-this-organization#161]
My MVP Profile is: https://mvp.microsoft.com/de-DE/MVP/profile/a235cc0c-1e9e-ed11-83ff-000d3a5600fa

- [X ] Send the invitation to my GitHub listed on my MVP profile above

or

- [ ] Send the invitation to my e-mail address listed on my MVP profile above

**Comment by augustoproiete** [comment]
Invite sent to https://github.com/JayRHa
