### ISSUE TITLE
Request to join this organization

### ISSUE THREAD

**Issue by qihangnet** [msmvps/join-this-organization#165]
My MVP Profile is: https://mvp.microsoft.com/zh-CN/MVP/profile/8f3e6042-2aaf-47f0-97c4-0de37cf0f81b

- [X] Send the invitation to my GitHub listed on my MVP profile above

**Comment by augustoproiete** [comment]
@qihangnet There's no public GitHub profile listed on your MVP profile... Ping this issue again once you add it

**Comment by qihangnet** [comment]
Sorry, I have updated now.Please review again.

**Comment by augustoproiete** [comment]
Invite sent to https://github.com/qihangnet
