### ISSUE TITLE
https://mvp.microsoft.com/en-us/PublicProfile/4030767?fullName=Alberto%20Diaz%20Martin

### ISSUE THREAD

**Issue by adiazcan** [msmvps/join-this-organization#17]
https://mvp.microsoft.com/en-us/PublicProfile/4030767?fullName=Alberto%20Diaz%20Martin

**Comment by adiazcan** [comment]
My github profile is https://github.com/adiazcan

**Comment by augustoproiete** [comment]
Invite sent to https://github.com/adiazcan
