### ISSUE TITLE
Request to join this organization

### ISSUE THREAD

**Issue by mivano** [msmvps/join-this-organization#171]
My MVP Profile is: https://mvp.microsoft.com/en-US/mvp/profile/92a33fd4-5889-496d-853e-8fa438d9e79e

- [ ] Send the invitation to my GitHub listed on my MVP profile above

or

- [ ] Send the invitation to my e-mail address listed on my MVP profile above

**Comment by augustoproiete** [comment]
Invite sent to https://github.com/mivano
