### ISSUE TITLE
Request to join this organization

### ISSUE THREAD

**Issue by lohitkolluri** [msmvps/join-this-organization#172]
My MVP Profile is: https://mvp.microsoft.com/en-US/studentambassadors/profile/bbc05c9f-f526-4e0e-8773-80417dcb38a0

- [x] Send the invitation to my GitHub listed on my MVP profile above

or

- [ ] Send the invitation to my e-mail address listed on my MVP profile above

**Comment by augustoproiete** [comment]
Invite sent https://github.com/lohitkolluri
