### ISSUE TITLE
Request to join this organization

### ISSUE THREAD

**Issue by samalavi** [msmvps/join-this-organization#173]
My MVP Profile is: https://mvp.microsoft.com/en-US/mvp/profile/3bcdb4b0-c755-ed11-9561-000d3a197333

- [x] Send the invitation to my GitHub listed on my MVP profile above

or

- [ ] Send the invitation to my e-mail address listed on my MVP profile above

**Comment by augustoproiete** [comment]
Invite sent to https://github.com/samalavi
