### ISSUE TITLE
Request to join this organization

### ISSUE THREAD

**Issue by lamrecognitions** [msmvps/join-this-organization#177]
My MVP Profile is: https://mvp.microsoft.com/en-US/mvp/profile/81ca1bc6-3959-ea11-a812-000d3a8ccb3e

- [ ] Send the invitation to my GitHub listed on my MVP profile above

or

- [ ] Send the invitation to my e-mail address listed on my MVP profile above

**Comment by augustoproiete** [comment]
Hi @lamrecognitions the GitHub profile linked on the MVP profile is https://github.com/anjoy8 whilst this request is coming from https://github.com/lamrecognitions - they don't seem to be the same person. Please clarify.

**Comment by augustoproiete** [comment]
Didn't hear back from you... https://github.com/anjoy8 is already a member of the org
