### ISSUE TITLE
Request to join this organization

### ISSUE THREAD

**Issue by TBBle** [msmvps/join-this-organization#178]
My MVP Profile is: https://mvp.microsoft.com/en-US/mvp/profile/370dc8f6-8016-4bc7-9770-6ef5fe2b37a1

- [x] Send the invitation to my GitHub listed on my MVP profile above

or

- [ ] Send the invitation to my e-mail address listed on my MVP profile above

**Comment by augustoproiete** [comment]
Invite sent to https://github.com/TBBle
