### ISSUE TITLE
Request to join this organization

### ISSUE THREAD

**Issue by johnlokerse** [msmvps/join-this-organization#179]
Hello 😃 

My MVP Profile is: https://mvp.microsoft.com/en-US/MVP/profile/9d148c3d-6dde-4fbf-bbc6-b2e67b27c28b

- [x] Send the invitation to my GitHub listed on my MVP profile above

or

- [ ] Send the invitation to my e-mail address listed on my MVP profile above

**Comment by augustoproiete** [comment]
Invite sent to https://github.com/johnlokerse
