### ISSUE TITLE
Request to join this organization

### ISSUE THREAD

**Issue by 239573049** [msmvps/join-this-organization#180]
My MVP Profile is: https://mvp.microsoft.com/en-US/mvp/profile/9dad415c-1eb1-4361-9088-f3dd0d402917

- [x] Send the invitation to my GitHub listed on my MVP profile above

or

- [ ] Send the invitation to my e-mail address listed on my MVP profile above

**Comment by augustoproiete** [comment]
Invite sent to https://github.com/239573049
