### ISSUE TITLE
Request to join this organization

### ISSUE THREAD

**Issue by rabbitism** [msmvps/join-this-organization#181]
My MVP Profile is: https://mvp.microsoft.com/en-US/MVP/profile/36daf396-ea5c-4f2e-8e62-211c32e8c3c6

- [x] Send the invitation to my GitHub listed on my MVP profile above

or

- [ ] Send the invitation to my e-mail address listed on my MVP profile above

**Comment by augustoproiete** [comment]
Invite sent to https://github.com/rabbitism
