### ISSUE TITLE
Request to join this organization

### ISSUE THREAD

**Issue by YSGStudyHards** [msmvps/join-this-organization#182]
My MVP Profile is: https://mvp.microsoft.com/en-us/mvp/profile/67a6d200-1c1d-43ee-8bf4-0a4d3d99224f

- [x]  Send the invitation to my GitHub listed on my MVP profile above

or

- [ ]  Send the invitation to my e-mail address listed on my MVP profile above

**Comment by augustoproiete** [comment]
Invite sent to https://github.com/YSGStudyHards
