### ISSUE TITLE
Request to join this organization

### ISSUE THREAD

**Issue by Balastrong** [msmvps/join-this-organization#183]
My MVP Profile is: https://mvp.microsoft.com/en-US/mvp/profile/51d820c5-949f-4961-aec5-09e34035cb24

- [x] Send the invitation to my GitHub listed on my MVP profile above

or

- [ ] Send the invitation to my e-mail address listed on my MVP profile above

**Comment by augustoproiete** [comment]
Invite sent to https://github.com/Balastrong
