### ISSUE TITLE
Request to join this organization

### ISSUE THREAD

**Issue by HotCakeX** [msmvps/join-this-organization#184]
My MVP Profile is: https://mvp.microsoft.com/en-US/mvp/profile/4edbca65-7979-4779-b7e4-d182e123259b

- [x] Send the invitation to my GitHub listed on my MVP profile above

or

- [ ] Send the invitation to my e-mail address listed on my MVP profile above

**Comment by augustoproiete** [comment]
Invite sent to https://github.com/HotCakeX
