### ISSUE TITLE
Request to join this organization

### ISSUE THREAD

**Issue by ruyut** [msmvps/join-this-organization#185]
My MVP Profile is: https://mvp.microsoft.com/en-US/mvp/profile/4be4fc33-f6ee-4322-85cb-b6c3106d9724

- [x] Send the invitation to my GitHub listed on my MVP profile above

or

- [ ] Send the invitation to my e-mail address listed on my MVP profile above

**Comment by augustoproiete** [comment]
Invite sent to https://github.com/ruyut

**Comment by ruyut** [comment]
@augustoproiete Thank You!
