### ISSUE TITLE
Request to join this organization

### ISSUE THREAD

**Issue by AndrewKeepCoding** [msmvps/join-this-organization#186]
My MVP Profile is: https://mvp.microsoft.com/en-US/MVP/profile/e2f2b8a5-25c8-4e03-8175-c689e4f8d3b6

- [x] Send the invitation to my GitHub listed on my MVP profile above

or

- [ ] Send the invitation to my e-mail address listed on my MVP profile above

**Comment by augustoproiete** [comment]
Invite sent to https://github.com/AndrewKeepCoding
