### ISSUE TITLE
Request to join this organization

### ISSUE THREAD

**Issue by witskeeper** [msmvps/join-this-organization#187]
My MVP Profile is: https://mvp.microsoft.com/en-us/MVP/profile/16e5bf1d-36d5-4b42-a7d3-c6651e11a9b1

- [x] Send the invitation to my GitHub listed on my MVP profile above

or

- [ ] Send the invitation to my e-mail address listed on my MVP profile above

**Comment by augustoproiete** [comment]
Invite sent to https://github.com/witskeeper

**Comment by witskeeper** [comment]
thank you
