### ISSUE TITLE
Request to join this organization

### ISSUE THREAD

**Issue by ahmedmuhi** [msmvps/join-this-organization#188]
My MVP Profile is: https://mvp.microsoft.com/en-US/MVP/profile/c21c4142-bd98-44cf-ad5a-7ac539f0e61b

- [ X] Send the invitation to my GitHub listed on my MVP profile above

or

- [ ] Send the invitation to my e-mail address listed on my MVP profile above

**Comment by augustoproiete** [comment]
Invite sent to https://github.com/ahmedmuhi
