### ISSUE TITLE
Request to join this organization

### ISSUE THREAD

**Issue by beinjamin** [msmvps/join-this-organization#189]
My MVP Profile is: https://mvp.microsoft.com/fr-FR/mvp/profile/64ac1b7b-3e8a-4dd8-9ef6-aded886ac34a

- [x] Send the invitation to my GitHub listed on my MVP profile above

or

- [x] Send the invitation to my e-mail address listed on my MVP profile above

**Comment by augustoproiete** [comment]
Invite sent to https://github.com/beinjamin
