### ISSUE TITLE
Request to join this organization

### ISSUE THREAD

**Issue by MassimoC** [msmvps/join-this-organization#190]
My MVP Profile is: https://mvp.microsoft.com/en-US/mvp/profile/8196a752-749a-4a88-9759-5a848e1a1594

- [x] Send the invitation to my GitHub listed on my MVP profile above

or

- [ ] Send the invitation to my e-mail address listed on my MVP profile above

**Comment by augustoproiete** [comment]
Invite sent to https://github.com/MassimoC
