### ISSUE TITLE
Request to join this organization

### ISSUE THREAD

**Issue by hishamco** [msmvps/join-this-organization#191]
My MVP Profile is: https://mvp.microsoft.com/en-US/MVP/profile/b3a86018-9c9b-487e-b865-d6ecca9ec032

- [ ] Send the invitation to my GitHub listed on my MVP profile above

or

- [ ] Send the invitation to my e-mail address listed on my MVP profile above

**Comment by augustoproiete** [comment]
Invite sent to https://github.com/hishamco

**Comment by hishamco** [comment]
Thanks a lot @augustoproiete
