### ISSUE TITLE
Request to join this organization

### ISSUE THREAD

**Issue by pthoor** [msmvps/join-this-organization#192]
My MVP Profile is: https://mvp.microsoft.com/en-US/MVP/profile/6fba834e-4a7f-ec11-8d21-0022482837b1

- [X] Send the invitation to my GitHub listed on my MVP profile above

or

- [ ] Send the invitation to my e-mail address listed on my MVP profile above

**Comment by augustoproiete** [comment]
Invite sent to https://github.com/pthoor
