### ISSUE TITLE
Request to join this organization

### ISSUE THREAD

**Issue by michaelmsonne** [msmvps/join-this-organization#193]
My MVP Profile is: https://mvp.microsoft.com/en-US/mvp/profile/b6a5bd91-5ebd-4c84-8965-023a95273093

- [x] Send the invitation to my GitHub listed on my MVP profile above

or

- [ ] Send the invitation to my e-mail address listed on my MVP profile above

**Comment by michaelmsonne** [comment]
Any news?

**Comment by michaelmsonne** [comment]
@augustoproiete

**Comment by augustoproiete** [comment]
Invite sent to https://github.com/michaelmsonne
