### ISSUE TITLE
Request to join this organization

### ISSUE THREAD

**Issue by wilsonwu** [msmvps/join-this-organization#198]
My MVP Profile is: https://mvp.microsoft.com/en-US/mvp/profile/654da68e-b0af-4878-a2eb-916f90ad82d6

- [x] Send the invitation to my GitHub listed on my MVP profile above

or

- [ ] Send the invitation to my e-mail address listed on my MVP profile above

**Comment by augustoproiete** [comment]
Invite sent to https://github.com/wilsonwu
