### ISSUE TITLE
rMVP Profile

### ISSUE THREAD

**Issue by rogeriocmelo** [msmvps/join-this-organization#20]
https://mvp.microsoft.com/en-us/PublicProfile/36795?fullName=Rogerio%20Melo

**Comment by augustoproiete** [comment]
Invite sent to your e-mail publicly listed on the rMVP Profile

![image](https://user-images.githubusercontent.com/177608/84435072-84bdc800-ac07-11ea-9b31-d355f261768b.png)


🇧🇷  👋🏻
