### ISSUE TITLE
Request to join this organization

### ISSUE THREAD

**Issue by pkhabazi** [msmvps/join-this-organization#204]
My MVP Profile is: https://mvp.microsoft.com/en-US/mvp/profile/be0eeeeb-f22e-eb11-a813-000d3a8ccaf5

- [x] Send the invitation to my GitHub listed on my MVP profile above

or

- [ ] Send the invitation to my e-mail address listed on my MVP profile above

**Comment by augustoproiete** [comment]
Invite sent to https://github.com/pkhabazi

**Comment by pkhabazi** [comment]
thanks @augustoproiete
