### ISSUE TITLE
Request to join this organization

### ISSUE THREAD

**Issue by xuzeyu91** [msmvps/join-this-organization#205]
My MVP Profile is: https://mvp.microsoft.com/zh-CN/mvp/profile/33b93083-918b-46dc-88ad-efd625db0ec4?fullName=xuzeyu

- [x] Send the invitation to my GitHub listed on my MVP profile above

**Comment by augustoproiete** [comment]
Invite sent to https://github.com/xuzeyu91

**Comment by xuzeyu91** [comment]
thanks
