### ISSUE TITLE
Request to join this organization

### ISSUE THREAD

**Issue by erudinsky** [msmvps/join-this-organization#206]
My MVP Profile is: https://mvp.microsoft.com/en-US/MVP/profile/33cf4dc8-f650-4422-a834-48c08ac92c58

- [ ] Send the invitation to my GitHub listed on my MVP profile above

or

- [ ] Send the invitation to my e-mail address listed on my MVP profile above

**Comment by augustoproiete** [comment]
Invite sent to https://github.com/erudinsky
