### ISSUE TITLE
Request to join this organization

### ISSUE THREAD

**Issue by Syncsecure** [msmvps/join-this-organization#207]
My MVP Profile is: https://mvp.microsoft.com/en-us/mvp/Rob%20Bos-5003719

- [ ] Send the invitation to my GitHub listed on my MVP profile above

or

- [ ] Send the invitation to my e-mail address listed on my MVP profile above

**Comment by augustoproiete** [comment]
Hi @Syncsecure the GitHub profile linked to the MVP profile you provided ( https://mvp.microsoft.com/en-us/mvp/Rob%20Bos-5003719 ) is https://github.com/rajbos @rajbos instead of https://github.com/Syncsecure ... Please advise

**Comment by augustoproiete** [comment]
@Syncsecure didn't hear back from you... Closing. Please open a new issue if relevant

**Comment by Syncsecure** [comment]
sry its my other github, there is my project github

**Comment by rajbos** [comment]
For good measure: I am Rob Bos and my MVP account is indeed https://mvp.microsoft.com/en-us/mvp/Rob%20Bos-5003719, which is a different person then is making the request here! I do not know who that is.

**Comment by augustoproiete** [comment]
Thanks @rajbos for checking-in...

@Syncsecure that's not nice... Reporting you to GitHub 🛃
