### ISSUE TITLE
Request to join this organization

### ISSUE THREAD

**Issue by krukowskid** [msmvps/join-this-organization#208]
My MVP Profile is: https://mvp.microsoft.com/MVP/profile/6f0273ae-cd46-4da6-944a-d8553a4854ef

- [X] Send the invitation to my GitHub listed on my MVP profile above

or

- [ ] Send the invitation to my e-mail address listed on my MVP profile above

**Comment by augustoproiete** [comment]
Invite sent to https://github.com/krukowskid
