### ISSUE TITLE
Request to join this organization

### ISSUE THREAD

**Issue by christianhelle** [msmvps/join-this-organization#209]
My MVP Profile is: https://mvp.microsoft.com/en-US/mvp/profile/e343a429-7b0d-ed11-b83f-000d3a1036b3

- [x] Send the invitation to my GitHub listed on my MVP profile above

or

- [ ] Send the invitation to my e-mail address listed on my MVP profile above

**Comment by vickyqu115** [comment]
My MVP Profile is: [https://mvp.microsoft.com/en-US/MVP/profile/ca186d6d-b3c7-428b-aab1-9479a4145041](https://mvp.microsoft.com/en-US/MVP/profile/ca186d6d-b3c7-428b-aab1-9479a4145041)

 - [ ] Send the invitation to my GitHub listed on my MVP profile above

or

 - [x] Send the invitation to my e-mail address listed on my MVP profile above

**Comment by augustoproiete** [comment]
Invite sent to https://github.com/christianhelle
