### ISSUE TITLE
Request to join this organization

### ISSUE THREAD

**Issue by lindexi** [msmvps/join-this-organization#21]
My MVP Profile is: https://mvp.microsoft.com/zh-cn/PublicProfile/5003260

- [x] Send the invitation to my GitHub user @lindexi listed on my MVP profile above

**Comment by augustoproiete** [comment]
@lindexi I don't see your GitHub profile listed in your MVP profile. I sent the invite to your e-mail listed there.

![image](https://user-images.githubusercontent.com/177608/84508286-7075db80-ac98-11ea-9058-67343c7c767a.png)
