### ISSUE TITLE
Request to join this organization

### ISSUE THREAD

**Issue by ianchen0119** [msmvps/join-this-organization#210]
My MVP Profile is: https://mvp.microsoft.com/zh-TW/MVP/profile/f6ebc818-673d-4561-b09b-5454b7e5aaef

- [x] Send the invitation to my GitHub listed on my MVP profile above

or

- [ ] Send the invitation to my e-mail address listed on my MVP profile above

**Comment by augustoproiete** [comment]
Invite sent to https://github.com/ianchen0119
