### ISSUE TITLE
Request to join this organization

### ISSUE THREAD

**Issue by rufer7** [msmvps/join-this-organization#212]
My MVP Profile is: https://mvp.microsoft.com/en-US/MVP/profile/f69d4145-5bf6-4708-8aae-8824cdb3bf46

- [x] Send the invitation to my GitHub listed on my MVP profile above

or

- [ ] Send the invitation to my e-mail address listed on my MVP profile above

**Comment by augustoproiete** [comment]
Invite sent to https://github.com/rufer7
