### ISSUE TITLE
Request to join this organization

### ISSUE THREAD

**Issue by ElectNewt** [msmvps/join-this-organization#214]
My MVP Profile is: https://mvp.microsoft.com/es-ES/MVP/profile/91a9bb7b-beca-4132-b01e-63cb235edfab

- [x] Send the invitation to my GitHub listed on my MVP profile above

or

- [ ] Send the invitation to my e-mail address listed on my MVP profile above

thanks.

**Comment by augustoproiete** [comment]
Invite sent to https://github.com/ElectNewt
