### ISSUE TITLE
Request to join this organization 

### ISSUE THREAD

**Issue by RoyKimYYZ** [msmvps/join-this-organization#215]
My MVP Profile is: https://mvp.microsoft.com/en-US/mvp/profile/bb44ba9a-a042-e711-8112-3863bb2ed1f8

- [x ] Send the invitation to my GitHub listed on my MVP profile above

or

- [x] Send the invitation to my e-mail address listed on my MVP profile above

**Comment by augustoproiete** [comment]
Invite sent to https://github.com/roykimyyz
