### ISSUE TITLE
Request to join this organization

### ISSUE THREAD

**Issue by fiseni** [msmvps/join-this-organization#216]
My MVP Profile is: https://mvp.microsoft.com/en-US/mvp/profile/e7a8d194-76ef-eb11-94ef-000d3a121a8b

- [x] Send the invitation to my GitHub listed on my MVP profile above

or

- [ ] Send the invitation to my e-mail address listed on my MVP profile above

**Comment by augustoproiete** [comment]
Invite sent to https://github.com/fiseni
