### ISSUE TITLE
Request to join this organization

### ISSUE THREAD

**Issue by fanslead** [msmvps/join-this-organization#217]
My MVP Profile is: https://mvp.microsoft.com/en-US/MVP/profile/d69595ed-3f31-4104-9e68-df24bb047dd6

- [x] Send the invitation to my GitHub listed on my MVP profile above

or

- [ ] Send the invitation to my e-mail address listed on my MVP profile above

**Comment by augustoproiete** [comment]
Invite sent to https://github.com/fanslead
