### ISSUE TITLE
Request to join this organization

### ISSUE THREAD

**Issue by Flow-Joe** [msmvps/join-this-organization#218]
My MVP Profile is: https://mvp.microsoft.com/en-US/mvp/profile/c35921ee-ec9f-ea11-a811-000d3a8ccaf5

- [x] Send the invitation to my GitHub listed on my MVP profile above

or

- [ ] Send the invitation to my e-mail address listed on my MVP profile above

**Comment by augustoproiete** [comment]
Invite sent to https://github.com/Flow-Joe
