### ISSUE TITLE
Request to join this organization

### ISSUE THREAD

**Issue by daryllabar** [msmvps/join-this-organization#22]
My MVP Profile is: https://mvp.microsoft.com/en-us/PublicProfile/5002010?fullName=Daryl%20%20LaBar

[x] Send the invitation to my GitHub user `your-github-username` listed on my MVP profile above

or

[ ] Send the invitation to my e-mail address `your@email.com` listed on my MVP profile above

**Comment by augustoproiete** [comment]
Invite sent to https://github.com/daryllabar
