### ISSUE TITLE
Request to join this organization

### ISSUE THREAD

**Issue by dbafromthecold** [msmvps/join-this-organization#25]
My MVP Profile is: https://mvp.microsoft.com/en-us/PublicProfile/5002905?fullName=Andrew%20Pruski

- [X] Send the invitation to my GitHub user `your-github-username` listed on my MVP profile above

or

- [ ] Send the invitation to my e-mail address `your@email.com` listed on my MVP profile above

**Comment by augustoproiete** [comment]
Invitation sent to https://github.com/dbafromthecold
