### ISSUE TITLE
Request to join this organization

### ISSUE THREAD

**Issue by pictos** [msmvps/join-this-organization#26]
My MVP Profile is: https://mvp.microsoft.com/en-us/PublicProfile/5003788?fullName=Pedro%20%20

- [x] Send the invitation to my GitHub user `your-github-username` listed on my MVP profile above

or

- [ ] Send the invitation to my e-mail address listed on my MVP profile above

**Comment by augustoproiete** [comment]
Invite sent to https://github.com/pictos
