### ISSUE TITLE
Request to join this organization

### ISSUE THREAD

**Issue by PowershellScripts** [msmvps/join-this-organization#27]
My MVP Profile is: https://mvp.microsoft.com/en-us/PublicProfile/5002299?fullName=Arleta%20Wanat

 - [x] Send the invitation to arleta.wanat@gmail.com - I edited the visibility in MVP profile, but it make take a while to change

- [ ] my GitHub listed on my MVP profile above

or

 - [ ] Send the invitation to my e-mail address listed on my MVP profile above

**Comment by augustoproiete** [comment]
Cześć @PowershellScripts!

It don't yet see your e-mail listed of your MVP Profile, but I do see your GitHub profile there - https://github.com/PowershellScripts.

Let me know if I should send the invite to your GitHub user directly

**Comment by augustoproiete** [comment]
@PowershellScripts I didn't hear from you so I've sent the invite to the GitHub listed in your MVP profile: https://github.com/PowershellScripts

![image](https://user-images.githubusercontent.com/177608/86065329-b4613280-ba45-11ea-8b59-92ee7b112c17.png)
