### ISSUE TITLE
Request to join this organization

### ISSUE THREAD

**Issue by ThorstenHans** [msmvps/join-this-organization#29]
My MVP Profile is: https://mvp.microsoft.com/en-us/PublicProfile/4032617?fullName=Thorsten%20Hans

- [x] Send the invitation to my GitHub listed on my MVP profile above

**Comment by augustoproiete** [comment]
Invite sent to https://github.com/ThorstenHans

**Comment by ThorstenHans** [comment]
thank you 👍
