### ISSUE TITLE
Request to join

### ISSUE THREAD

**Issue by dracan** [msmvps/join-this-organization#3]
https://mvp.microsoft.com/en-us/PublicProfile/5003462

**Comment by augustoproiete** [comment]
Invite sent to https://github.com/dracan

**Comment by dracan** [comment]
Hi @augustoproiete - I didn't get an invite through.

**Comment by augustoproiete** [comment]
@dracan I see you've joined the organization, so I'm assuming you found the invite. Let me know if you need help.

![image](https://user-images.githubusercontent.com/177608/84413399-f33e5e00-abe6-11ea-871f-364f741ac64a.png)

**Comment by dracan** [comment]
Ah, you sent me that invite before I even knew this org existed. That's what I clicked on which directed me to the readme which then asked to create an issue with a link to my MVP profile.
