### ISSUE TITLE
Request to join this organization

### ISSUE THREAD

**Issue by CarlosLanderas** [msmvps/join-this-organization#32]
My MVP Profile is: 

https://mvp.microsoft.com/en-us/PublicProfile/5003037?fullName=Carlos%20%20Landeras

- [x] Send the invitation to my GitHub listed on my MVP profile above

**Comment by augustoproiete** [comment]
Invite sent to https://github.com/CarlosLanderas

🇪🇸 !

**Comment by CarlosLanderas** [comment]
Thanks @augustoproiete !!!
