### ISSUE TITLE
Request to join this organization

### ISSUE THREAD

**Issue by hupo376787** [msmvps/join-this-organization#39]
My MVP Profile is: [https://mvp.microsoft.com/en-us/PublicProfile/5003917?fullName=Zheng%20Wang](https://mvp.microsoft.com/en-us/PublicProfile/5003917?fullName=Zheng%20Wang)

- [x] Send the invitation to my GitHub listed on my MVP profile above

or

- [ ] Send the invitation to my e-mail address listed on my MVP profile above

**Comment by augustoproiete** [comment]
Invite sent to https://github.com/hupo376787
