### ISSUE TITLE
Request to join this organization

### ISSUE THREAD

**Issue by DrBushyTop** [msmvps/join-this-organization#40]
My MVP Profile is: https://mvp.microsoft.com/en-us/PublicProfile/5003781?fullName=Pasi%20%20Huuhka

- [x] Send the invitation to my GitHub listed on my MVP profile above

or

- [ ] Send the invitation to my e-mail address listed on my MVP profile above

**Comment by augustoproiete** [comment]
Invite sent to https://github.com/DrBushyTop
