### ISSUE TITLE
Request to join this organization

### ISSUE THREAD

**Issue by J0rgeSerran0** [msmvps/join-this-organization#47]
My MVP Profile is: https://mvp.microsoft.com/en-us/PublicProfile/8633?fullName=Jorge%20Serrano%20Perez

- [X] Send the invitation to my GitHub listed on my MVP profile above

or

- [ ] Send the invitation to my e-mail address listed on my MVP profile above

**Comment by augustoproiete** [comment]
Invite sent!
:es:!
