### ISSUE TITLE
a link in README.md can't open

### ISSUE THREAD

**Issue by anjoy8** [msmvps/join-this-organization#49]
Dear msmvps, 
hope this message finds you well. 

I recently find that the link "https://mvp.microsoft.com" can't be opend in README.md page.

Because there is a "%5D" unnecessary after the href link, as the image shown below.
![image](https://user-images.githubusercontent.com/28941816/99892396-6fb58c80-2caf-11eb-8140-ab472b7fbece.png)

**Comment by augustoproiete** [comment]
Thanks for reporting, @anjoy8! Would you like to send a pull-request to fix it?
If not, no worries and I'll fix it shortly.

**Comment by anjoy8** [comment]
ok, I send a pull-request right now
