### ISSUE TITLE
Request to join this organization

### ISSUE THREAD

**Issue by codingbandit** [msmvps/join-this-organization#53]
My MVP Profile is: https://mvp.microsoft.com/en-us/mvp/Carey%20Payette-5003966

- [x] Send the invitation to my GitHub listed on my MVP profile above

or

- [ ] Send the invitation to my e-mail address listed on my MVP profile above

**Comment by augustoproiete** [comment]
Hey Carey, your GitHub profile URL is not listed in your MVP profile so I can't send the invite directly to your user. I sent an invitation to the e-mail you have listed in the MVP profile though so hopefully you can accept with your GH account.

Feel free to reopen if you need the invite sent to your GitHub user instead (once you update the MVP profile)

![image](https://user-images.githubusercontent.com/177608/102383350-cc038780-3fa1-11eb-9f0a-3d711e473ba9.png)
