### ISSUE TITLE
Request to join this organization

### ISSUE THREAD

**Issue by rvinothrajendran** [msmvps/join-this-organization#59]
My MVP Profile is: https://mvp.microsoft.com/en-us/PublicProfile/5003631?fullName=Vinoth%20Rajendran

- [ X ] Send the invitation to my GitHub listed on my MVP profile above

or

- [ ] Send the invitation to my e-mail address listed on my MVP profile above

**Comment by augustoproiete** [comment]
Hey @rvinothrajendran I don't see a GitHub profile on the link above. Could you add or change the visibility?

![image](https://user-images.githubusercontent.com/177608/111037946-c086f780-83fc-11eb-9e6e-7d6708523c4a.png)

**Comment by rvinothrajendran** [comment]
@augustoproiete Kindly check now

**Comment by augustoproiete** [comment]
Perfect. Thanks! Invite sent to https://github.com/rvinothrajendran
