### ISSUE TITLE
Request to join this organization

### ISSUE THREAD

**Issue by geffzhang** [msmvps/join-this-organization#60]
My MVP Profile is: https://mvp.microsoft.com/en-us/PublicProfile/33797?fullName=Shanyou%20Zhang

- [ ] Send the invitation to my GitHub listed on my MVP profile above
 [https://github.com/geffzhang](https://github.com/geffzhang)

**Comment by augustoproiete** [comment]
Invite sent to https://github.com/geffzhang ! 🇨🇳
