### ISSUE TITLE
Request to join this organization

### ISSUE THREAD

**Issue by jefutte** [msmvps/join-this-organization#62]
My MVP Profile is: https://mvp.microsoft.com/en-us/PublicProfile/5002453?fullName=Jesper%20F%C3%BCtterer%20Jensen

- [ ] Send the invitation to my GitHub listed on my MVP profile above

**Comment by augustoproiete** [comment]
Hey @jefutte, your GitHub profile is not listed in your MVP profile (or is marked as private)

![image](https://user-images.githubusercontent.com/177608/117153823-b4cb0800-ad91-11eb-97ae-994fbf1fe49d.png)

**Comment by jefutte** [comment]
@augustoproiete - hmm, must be on the way then, I changed the status and even added a new entry to see it. Will check and update here when it's showing up - thanks :)

![image](https://user-images.githubusercontent.com/8363820/117155892-78150600-adbd-11eb-872c-8f7a4ca5845e.png)

**Comment by augustoproiete** [comment]
MVP website was updated :tada:. Invite sent to https://github.com/jefutte

![image](https://user-images.githubusercontent.com/177608/117390925-5dc64f80-aec5-11eb-8269-cbba8b1dfe0d.png)
