### ISSUE TITLE
Request to join this organization

### ISSUE THREAD

**Issue by WeihanLi** [msmvps/join-this-organization#66]
My MVP Profile is: <https://mvp.microsoft.com/en-us/PublicProfile/5004222>

- [x] Send the invitation to my GitHub listed on my MVP profile above

https://github.com/WeihanLi

**Comment by augustoproiete** [comment]
Hey @WeihanLi the link you sent doesn't seem like the official website, I suspect it's a copy of Microsoft's website specific for China?

Anyway, I was able to find your profile on https://mvp.microsoft.com/en-us/PublicProfile/5004222?fullName=Weihan%20Li 
 so invite sent to https://github.com/WeihanLi

**Comment by WeihanLi** [comment]
Thanks @augustoproiete , I just updated the link.
