### ISSUE TITLE
join mvp

### ISSUE THREAD

**Issue by JusterZhu** [msmvps/join-this-organization#72]
https://mvp.microsoft.com/zh-cn/PublicProfile/5004326?fullName=zhen%20zhu

**Comment by augustoproiete** [comment]
Invite sent to your public email listed on the profile `zhuzhen723723@outlook.com`

![image](https://user-images.githubusercontent.com/177608/127905016-5b74b1e7-654c-47ed-9483-a6cb1ca13c85.png)

**Comment by JusterZhu** [comment]
I don’t see the invitation email in my mailbox

**Comment by WeihanLi** [comment]
Try to access <https://github.com/msmvps> with the related GitHub account

**Comment by JusterZhu** [comment]
got it
