### ISSUE TITLE
Request to join this organization

### ISSUE THREAD

**Issue by shinyzhu** [msmvps/join-this-organization#74]
My MVP Profile is: https://mvp.microsoft.com/en-us/PublicProfile/4020683?fullName=Shiny%20Zhu

- [x] Send the invitation to my GitHub listed on my MVP profile above

or

- [ ] Send the invitation to my e-mail address listed on my MVP profile above

**Comment by augustoproiete** [comment]
Invite sent to https://github.com/shinyzhu
