### ISSUE TITLE
Request to join this organization

### ISSUE THREAD

**Issue by whuanle** [msmvps/join-this-organization#77]
My MVP Profile is: https://mvp.microsoft.com/en-us/PublicProfile/5004445?fullName=Zhenfan%20Yan

- [x] Send the invitation to my GitHub listed on my MVP profile above

or

- [ ] Send the invitation to my e-mail address listed on my MVP profile above

**Comment by augustoproiete** [comment]
Hey @whuanle looks like your GitHub profile is private on your MVP page. Could you make it public?

![image](https://user-images.githubusercontent.com/177608/132079619-2815ef2c-50b6-441a-bba1-5019ea1f707a.png)

**Comment by whuanle** [comment]
Wait a moment

**Comment by whuanle** [comment]
![image](https://user-images.githubusercontent.com/2189761/132080531-a9dbfc67-9d08-4556-a8e2-c373fcee0203.png)
![image](https://user-images.githubusercontent.com/2189761/132080533-5712f659-7ba9-4dfb-be3c-1747a2eec2eb.png)
For some reason, it has been unable to display.

**Comment by augustoproiete** [comment]
If you can create an activity in your MVP profile that includes a link to your GitHub profile that works too, or alternatively make your email address public on your MVP profile and I can send the invite via email instead.

**Comment by whuanle** [comment]
Now it's finally working... 
https://mvp.microsoft.com/en-us/PublicProfile/5004445?fullName=Zhenfan%20Yan
@augustoproiete

**Comment by augustoproiete** [comment]
Great! Invite sent to https://github.com/whuanle
