### ISSUE TITLE
Request to join this organization

### ISSUE THREAD

**Issue by vukasinterzic** [msmvps/join-this-organization#80]
My MVP Profile is: https://mvp.microsoft.com/en-us/PublicProfile/5003864?fullName=Vukasin%20Terzic

- [X ] Send the invitation to my GitHub listed on my MVP profile above

**Comment by augustoproiete** [comment]
Invite sent to https://github.com/vukasinterzic

**Comment by vukasinterzic** [comment]
thank you for adding me ;)
