### ISSUE TITLE
Request to join this organization

### ISSUE THREAD

**Issue by tao12345666333** [msmvps/join-this-organization#84]
My MVP Profile is: https://mvp.microsoft.com/en-us/PublicProfile/5004660?fullName=Jintao%20Zhang

- [x] Send the invitation to my GitHub listed on my MVP profile above

**Comment by augustoproiete** [comment]
@tao12345666333 There's no GitHub profile on the MVP profile you linked:

![image](https://user-images.githubusercontent.com/177608/149075971-77ec6344-9984-4501-a026-ccec05ae9d8f.png)

**Comment by tao12345666333** [comment]
sorry, let me change the settings.

**Comment by tao12345666333** [comment]
![2022-01-12 23-00-09屏幕截图](https://user-images.githubusercontent.com/3264292/149165235-0f3572bb-965c-420b-8016-788e46414360.png)
I've changed it's visibility to everyone, but it's not showing up in my MVP profile yet. Maybe I need to wait for it to finish updating automatically.

**Comment by augustoproiete** [comment]
Cool, it's probably a caching issue. I'll check it again tomorrow

**Comment by tao12345666333** [comment]
Thanks!

**Comment by augustoproiete** [comment]
Invite sent to https://github.com/tao12345666333
