### ISSUE TITLE
Request to join this organization

### ISSUE THREAD

**Issue by jessehouwing** [msmvps/join-this-organization#85]
My MVP Profile is: https://mvp.microsoft.com/en-us/PublicProfile/5001511?fullName=Jesse%20Houwing

- [x] Send the invitation to my GitHub listed on my MVP profile above

**Comment by augustoproiete** [comment]
@jessehouwing You are already a member of this organization... Let me know if I missed anything

**Comment by jessehouwing** [comment]
There used to be more repos here, but it seems they were moved to teams. I'd thought something had gone wrong with my membership.

Thanks for checking.
