### ISSUE TITLE
Request to join this organization

### ISSUE THREAD

**Issue by KuiMing** [msmvps/join-this-organization#92]
My MVP Profile is: https://mvp.microsoft.com/zh-cn/PublicProfile/5004774?fullName=Kui-Ming%20Chen

**Comment by augustoproiete** [comment]
Hi, your Github profile is not visible in your MVP profile:

<img width="274" alt="image" src="https://user-images.githubusercontent.com/177608/163167753-e01e37ae-39e5-43fb-ba41-0deaac6021e7.png">

**Comment by augustoproiete** [comment]
I sent an invite to the email listed above in the screenshot
