### ISSUE TITLE
Request to join this organization

### ISSUE THREAD

**Issue by vraposo** [msmvps/join-this-organization#97]
My MVP Profile is: https://mvp.microsoft.com/en-us/PublicProfile/4038280?fullName=Virgilio%20Esteves

- [ ] Send the invitation to my GitHub listed on my MVP profile above

or

- [X] Send the invitation to my e-mail address listed on my MVP profile above

**Comment by augustoproiete** [comment]
Invite sent to https://github.com/vraposo

Abraço Virgílio!! 🇵🇹
