### ISSUE TITLE
Request to join this organization

### ISSUE THREAD

**Issue by ddobric** [msmvps/join-this-organization#98]
My MVP Profile is: [https://mvp.microsoft.com/en-us/PublicProfile/4020449?fullName=Damir%20Dobric](https://mvp.microsoft.com/en-us/PublicProfile/4020449?fullName=Damir%20Dobric )

- [ ] Send the invitation to my GitHub listed on my MVP profile above

or

- [X] Send the invitation to my e-mail address listed on my MVP profile above

**Comment by augustoproiete** [comment]
@ddobric You have already joined the org. Let me know if there's anything else missing
